### PR TITLE
feat: added file reporter

### PR DESCRIPTION
**Pull request by di5abled**
another try :)

hope you like this more, really basic for the first version

### CODE REVIEW

**Comment by JustBlackBird** [comment]
Cool, you're right I like it :+1: Great job!

The only thing I cannot understand is why don't you use a callback function in `fs.writeFile` ([here](https://github.com/di5abled/gulp-phpcs/commit/7c6a1f094ff51fa200f41d6e77a410c67d49f0c8#diff-960bdd414167b0c7380b4caa8eee6c83R47)).

Also there are several minor problems (mostly with codding style and output consistency) but I can fix them by myself after merge.

**Comment by di5abled** [comment]
Hy,

true story, I fixed this.

**Comment by JustBlackBird** [comment]
Thank you. I've fix some problems, and release a new version after a while

**Comment by di5abled** [comment]
nice, hope you can release a new version soon ;)

**Comment by di5abled** [comment]
when will you bump the version?
want to use this feature on my current project :)

**Comment by JustBlackBird** [comment]
The next version will be release right after I'll fix #19 (there were some changes in plugin's logic so I want to make sure everything is fine). If nothing will brake my plans I could finish today or tomorrow.

**Comment by JustBlackBird** [comment]
Done!

**Pull request merged**
