### PR TITLE
added phpcs report options

### PR DESCRIPTION
**Pull request by di5abled**
and changed reporters to failOnError reporters to prevent conflicts in understanding

#11

### CODE REVIEW

**Comment by JustBlackBird** [comment]
So why don't you just create a reporter that saves reports to file?

**Comment by JustBlackBird** [comment]
Also PHPCS running logic was intentionally decoupled from reporting stuff some time ago (see https://github.com/JustBlackBird/gulp-phpcs/commit/b60632d33484bb9478ac6c6788e546680a917c1b). And I've already describe my position about `--reportFile` option [here](https://github.com/JustBlackBird/gulp-phpcs/pull/12#issuecomment-126200257).

**Comment by di5abled** [comment]
Why should I mimic the functionality someone already die in phpcs and rewrite them as an reporter if I could just use the build in phpcs ones. This makes no sense for me!?

I saw you comments on that and thouht this would be a solution to combine this two solutions.

So you see no way using also the native phpcs reporting options?

**Comment by di5abled** [comment]
I had another closer look at how everything is put together, I get the problem now, I'll have a look at a custom reporter :)

**Comment by JustBlackBird** [comment]
> So you see no way using also the native phpcs reporting options?

I don't have anything against `--report` option, but I don't want to mix native PHPCS reporting to file with reporters already implemented in gulp-phpcs. It will end up with a mess.

**Pull request closed without merging**
