### PR TITLE
Add reporting option

### PR DESCRIPTION
**Pull request by culleningus**
Extend allowed options to include reporting

### CODE REVIEW

**Comment by JustBlackBird** [comment]
`report` option LGTM, but I don't like `reportFile` option. Also you should add some docs about option usage to readme.

**Comment by culleningus** [comment]
Yeah I saw that you allow custom reporters but it would be good to get the standard phpcs functionality.

How do you think we could going about getting the standard report types?

**Comment by JustBlackBird** [comment]
> Yeah I saw that you allow custom reporters but it would be good to get the standard phpcs functionality.

If both `gulp-phpcs` reporters and PHPCS itself will output something somewhere it will be a mess. So, for consistency reasons, all output should be done with `gulp-phpcs` reporters.

> How do you think we could going about getting the standard report types?

As I see `--report` PHPCS options does the job.

**Comment by culleningus** [comment]
Okay I get you, I'll clean that up and some docs.

**Comment by JustBlackBird** [comment]
I could not merge this automatically anymore. Sorry, but I have to close the PR. At the same time, I'll reopen it once you make changes we were talking about.

**Comment by naunod** [comment]
Hi there!
I was interested by this PR. @culleningus said he got you @JustBlackBird but I did not! :)
How can you define the report format? Indeed, with PHPCS you can use `--report` paramter to choose the format ('checkstyle' for instance).
How can you do that with `gulp-phpcs`?
Thanks in advance!

**Comment by JustBlackBird** [comment]
You've missed my point. I have nothing against `--report` option but I don't want merge a PR with `--reportFile` option.

**Pull request closed without merging**
